{
  "formatVersion": "1.1",
  "component": {
    "group": "xyz.selenus.luna",
    "module": "luna-sdk",
    "version": "5.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "xyz.selenus.luna",
          "module": "luna-core",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "xyz.selenus.luna",
          "module": "luna-rpc",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "xyz.selenus.luna",
          "module": "luna-das",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "xyz.selenus.luna",
          "module": "luna-webhooks",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "xyz.selenus.luna",
          "module": "luna-priority",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "xyz.selenus.luna",
          "module": "luna-enhanced-tx",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "xyz.selenus.luna",
          "module": "luna-analytics",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "xyz.selenus.luna",
          "module": "luna-innovations",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "xyz.selenus.luna",
          "module": "luna-privacy",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "xyz.selenus.luna",
          "module": "luna-jupiter",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "luna-sdk-5.3.0.jar",
          "url": "luna-sdk-5.3.0.jar",
          "size": 261,
          "sha512": "91d485eff6742571eb9b5b2c023def977a7537e66073062205cdf6c3c22d2dfe80a0d0dde59df7fd6a957972c6f54d2e1706527a11c41fc8d8eb57dfe4b00d12",
          "sha256": "78ae4b66a0ddf617c792cc25f2bb1eff982a0f23a4f548fff292e22154a446a2",
          "sha1": "0f24ef67ad78747ac1427c6bcd5c869f843bca92",
          "md5": "66cdb72816281e78d6a566b29ddd8d18"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "xyz.selenus.luna",
          "module": "luna-core",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "xyz.selenus.luna",
          "module": "luna-rpc",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "xyz.selenus.luna",
          "module": "luna-das",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "xyz.selenus.luna",
          "module": "luna-webhooks",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "xyz.selenus.luna",
          "module": "luna-priority",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "xyz.selenus.luna",
          "module": "luna-enhanced-tx",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "xyz.selenus.luna",
          "module": "luna-analytics",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "xyz.selenus.luna",
          "module": "luna-innovations",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "xyz.selenus.luna",
          "module": "luna-privacy",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "xyz.selenus.luna",
          "module": "luna-jupiter",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "luna-sdk-5.3.0.jar",
          "url": "luna-sdk-5.3.0.jar",
          "size": 261,
          "sha512": "91d485eff6742571eb9b5b2c023def977a7537e66073062205cdf6c3c22d2dfe80a0d0dde59df7fd6a957972c6f54d2e1706527a11c41fc8d8eb57dfe4b00d12",
          "sha256": "78ae4b66a0ddf617c792cc25f2bb1eff982a0f23a4f548fff292e22154a446a2",
          "sha1": "0f24ef67ad78747ac1427c6bcd5c869f843bca92",
          "md5": "66cdb72816281e78d6a566b29ddd8d18"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "luna-sdk-5.3.0-javadoc.jar",
          "url": "luna-sdk-5.3.0-javadoc.jar",
          "size": 261,
          "sha512": "91d485eff6742571eb9b5b2c023def977a7537e66073062205cdf6c3c22d2dfe80a0d0dde59df7fd6a957972c6f54d2e1706527a11c41fc8d8eb57dfe4b00d12",
          "sha256": "78ae4b66a0ddf617c792cc25f2bb1eff982a0f23a4f548fff292e22154a446a2",
          "sha1": "0f24ef67ad78747ac1427c6bcd5c869f843bca92",
          "md5": "66cdb72816281e78d6a566b29ddd8d18"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "luna-sdk-5.3.0-sources.jar",
          "url": "luna-sdk-5.3.0-sources.jar",
          "size": 561,
          "sha512": "76623d8683beb1e7e608772aadeef44148417ab7a64459c448ddf041f6d6a4d3661eae1cb7cd46bde2ebbf8ba30162e7a2e74eba2cd5f35c39be6cf580d15bbb",
          "sha256": "05030e0d44dcafac4ac20cf75b5664e6e2d8c75af31996fd534d115cb6891a9e",
          "sha1": "92bb87e6a6743807da3ba1bb25ceb79a99e1d8dd",
          "md5": "b06a405201205dd6fa176d4d9014cdef"
        }
      ]
    }
  ]
}
