{
  "formatVersion": "1.1",
  "component": {
    "group": "xyz.selenus.luna",
    "module": "luna-core",
    "version": "5.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "luna-core-5.3.0.jar",
          "url": "luna-core-5.3.0.jar",
          "size": 1290785,
          "sha512": "88fdc935cc2cd57878de55e3815c18833a1ee3457345c64cc05d9c22d7ef9434058a30b4bc0850eac5180580d202a09468669716d402c456aebbb2c352c5210a",
          "sha256": "ef05ec1c43bec894df857e8350d4db2b843376bdeb0a48dfb63ddfc4a09b8bce",
          "sha1": "294c737da8747aab208a4af8fb596e11eb1ecfc8",
          "md5": "45949670f350b1880054718112fdd2c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-sse",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-kotlin-stub",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.78.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-netty-shaded",
          "version": {
            "requires": "1.78.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-kotlin",
          "version": {
            "requires": "4.32.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "luna-core-5.3.0.jar",
          "url": "luna-core-5.3.0.jar",
          "size": 1290785,
          "sha512": "88fdc935cc2cd57878de55e3815c18833a1ee3457345c64cc05d9c22d7ef9434058a30b4bc0850eac5180580d202a09468669716d402c456aebbb2c352c5210a",
          "sha256": "ef05ec1c43bec894df857e8350d4db2b843376bdeb0a48dfb63ddfc4a09b8bce",
          "sha1": "294c737da8747aab208a4af8fb596e11eb1ecfc8",
          "md5": "45949670f350b1880054718112fdd2c0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "luna-core-5.3.0-javadoc.jar",
          "url": "luna-core-5.3.0-javadoc.jar",
          "size": 261,
          "sha512": "91d485eff6742571eb9b5b2c023def977a7537e66073062205cdf6c3c22d2dfe80a0d0dde59df7fd6a957972c6f54d2e1706527a11c41fc8d8eb57dfe4b00d12",
          "sha256": "78ae4b66a0ddf617c792cc25f2bb1eff982a0f23a4f548fff292e22154a446a2",
          "sha1": "0f24ef67ad78747ac1427c6bcd5c869f843bca92",
          "md5": "66cdb72816281e78d6a566b29ddd8d18"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "luna-core-5.3.0-sources.jar",
          "url": "luna-core-5.3.0-sources.jar",
          "size": 83256,
          "sha512": "d37781632ad9e5030d8896bbeacf87de0f37a563c3acb95f9ac4c9b68ecda01939c7922ec8c3db5ccb3580b91c346a2717516757e9d8a3a13d0310bb337d3721",
          "sha256": "ebffc7b3e3ecd4fdfbea991069ff8b475a4448840d0ebe3e6f006a64c2fb32a4",
          "sha1": "beed27244a7a754d5acae0e07739b5f19a7dbc85",
          "md5": "8cbf1c9e6f9a444fe2174336bb217002"
        }
      ]
    }
  ]
}
